apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-validation
  namespace: default
spec:
  selector:
    matchLabels:
      auth: jwt
  jwtRules:
    - issuer: https://aks-demo.vtch.tech/auth/realms/cluster
      jwksUri: https://aks-demo.vtch.tech/auth/realms/cluster/protocol/openid-connect/certs
      forwardOriginalToken: true
