apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: application-service
  namespace: default
spec:
  hosts:
    - "vtch-aks-demo.duckdns.org"
  gateways:
    - application-gateway
  http:
    - match:
        - uri:
            prefix: "/auth"
      route:
        - destination:
            port:
              number: 80
            host: keycloak-http
    - match:
        - uri:
            prefix: "/filestorage"
      route:
        - destination:
            port:
              number: 8080
            host: file-storage
    - match:
        - uri:
            prefix: "/persistence"
      route:
        - destination:
            port:
              number: 8081
            host: persistence-service
    - match:
        - uri:
            prefix: "/api/v2"
      route:
        - destination:
            port:
              number: 9411
            host: zipkin
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            port:
              number: 80
            host: frontend-service