apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: default
  labels:
    app: kafka
spec:
  kafka:
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      volumes:
      - type: persistent-claim
        size: 10Gi
        id: 0
      type: jbod
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1280Mi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 384Mi
        limits:
          memory: 512Mi
    userOperator:
      resources:
        requests:
          memory: 384Mi
        limits:
          memory: 512Mi