apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: default
  labels:
    app: kafka
spec:
  kafka:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - app
        tolerations:
          - key: "type"
            operator: Equal
            value: "app"
            effect: NoSchedule
    version: 3.4.1
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      volumes:
      - type: persistent-claim
        size: 10Gi
        id: 0
      type: jbod
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1280Mi
  zookeeper:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                    - app
        tolerations:
          - key: "type"
            operator: Equal
            value: "app"
            effect: NoSchedule
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 384Mi
        limits:
          memory: 512Mi
    userOperator:
      resources:
        requests:
          memory: 384Mi
        limits:
          memory: 512Mi
