apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: vtch-aks-demo-monitoring.duckdns.org
  issuerRef:
    name: letsencrypt
  dnsNames:
    - vtch-aks-demo-monitoring.duckdns.org