apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-cert
  namespace: istio-system
spec:
  secretName: main-cert
  commonName: aks-demo.vtch.tech
  issuerRef:
    name: letsencrypt
  dnsNames:
    - aks-demo.vtch.tech
