apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-cert
  namespace: istio-system
spec:
  secretName: main-cert
  commonName: vtch-aks-demo.duckdns.org
  issuerRef:
    name: letsencrypt
  dnsNames:
    - vtch-aks-demo.duckdns.org