apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-system
spec:
  secretName: argocd-cert
  commonName: argocd.aks-demo.vtch.tech
  issuerRef:
    name: letsencrypt
  dnsNames:
    - argocd.aks-demo.vtch.tech
