apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: default
  labels:
    app: file-storage
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: file-storage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: file-storage
        auth: jwt
    spec:
      nodeSelector:
        type: app
      containers:
        - name: file-storage
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud{{ if .Values.releaseToggles }},release-toggles{{ end }}"
            {{ if .Values.releaseToggles }}
            - name: TOGGLZ_RELEASE_TOGGLES_LIST
              value: {{ .Values.releaseToggles }}
            {{ end }}
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  key: STORAGE_ACCOUNT_KEY
                  name: file-storage-cloud-secret
            - name: STORAGE_CONNECTION
              valueFrom:
                secretKeyRef:
                  key: STORAGE_CONNECTION
                  name: file-storage-cloud-secret
            - name: FUNCTIONS_KEY
              valueFrom:
                secretKeyRef:
                  key: FUNCTIONS_KEY
                  name: file-storage-cloud-secret
            - name: ACTUATOR_USERNAME
              valueFrom:
                secretKeyRef:
                  key: ACTUATOR_USERNAME
                  name: file-storage-cloud-secret
            - name: ACTUATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ACTUATOR_PASSWORD
                  name: file-storage-cloud-secret
            - name: TOGGLZ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: TOGGLZ_USERNAME
                  name: file-storage-cloud-secret
            - name: TOGGLZ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: TOGGLZ_PASSWORD
                  name: file-storage-cloud-secret
          livenessProbe:
            httpGet:
              path: /filestorage/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /filestorage/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
#            - name: application-config
#              mountPath: "/etc/config/"
            - name: application-cloud-config
              mountPath: "/etc/config/cloud/"
#            - name: file-storage-pv
#              mountPath: "/etc/file-storage/uploads"
        - name: hazelcast
          imagePullPolicy: IfNotPresent
          image: hazelcast/hazelcast:4.2
          env:
            - name: JAVA_OPTS
              value: >-
                -Dhazelcast.rest.enabled=true
                -Dhazelcast.config=/data/hazelcast/hazelcast.yaml
                -Dhazelcast.shutdownhook.policy=GRACEFUL
                -Dhazelcast.shutdownhook.enabled=true
                -Dhazelcast.graceful.shutdown.max.wait=600
          ports:
            - name: hazelcast
              containerPort: 5701
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /hazelcast/health/node-state
              port: 5701
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - name: hazelcast-storage
              mountPath: /data/hazelcast
      volumes:
#        - name: file-storage-pv
#          persistentVolumeClaim:
#            claimName: file-storage-pvc
#        - name: application-config
#          configMap:
#            name: file-storage-config
#            items:
#              - key: application-prod.yml
#                path: application-prod.yml
        - name: application-cloud-config
          configMap:
            name: file-storage-cloud-config
            items:
              - key: application-cloud.yml
                path: application-cloud.yml
        - name: hazelcast-storage
          configMap:
            name: file-storage-hazelcast-config