apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: file-storage
  name: file-storage-config
  namespace: default
data:
  application-prod.yml: |-
    spring:
      kafka:
        bootstrap-servers: kafka-cluster-kafka-brokers.default.svc.cluster.local:9092
    server:
      servlet:
        context-path: /filestorage
    grpc:
      client:
        persistence:
          host: persistence-service.default.svc.cluster.local
          port: 9090
    management:
      security:
        username: ${ACTUATOR_USERNAME}
        password: ${ACTUATOR_PASSWORD}
    togglz:
      console:
        username: ${TOGGLZ_USERNAME}
        password: ${TOGGLZ_PASSWORD}
    application:
      hostname: https://vtch-aks-demo.duckdns.org
      upload.path: /etc/file-storage/uploads/
      persistence.url: http://persistence-service.default.svc.cluster.local:8081/persistence/api/v1/messages
      token.url: https://vtch-aks-demo.duckdns.org/auth/realms/cluster/protocol/openid-connect/token
      functions.key: ${FUNCTIONS_KEY}
      kafka:
        topic: auditing
        stream:
          topic: reverse-auditing
      cors:
        allowed.origins: https://vtch-aks-demo.duckdns.org
        allowed.methods: GET, POST, PUT, DELETE
