apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: falco
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: falco
    helm:
      valueFiles:
        - values.yaml
      values: |-
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
          - key: "type"
            operator: Equal
            value: "app"
            effect: NoSchedule
      parameters:
        - name: falco.jsonOutput
          value: 'true'
        - name: falco.logSyslog
          value: 'false'
        - name: falco.priority
          value: warning
        - name: falco.logLevel
          value: warning
    repoURL: 'https://falcosecurity.github.io/charts'
    targetRevision: 1.15.3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
