apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-storage
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: image.tag
          value: {{ .Values.image.tag }}
        - name: releaseToggles
    path: aks/filestorage
    repoURL: 'https://github.com/valtech-ch/microservice-kubernetes-cluster.git'
    targetRevision: main
