apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  revisionHistoryLimit: 3
  source:
    chart: fluentd-elasticsearch
    helm:
      valueFiles:
        - values.yaml
      values: |-
        tolerations:
          - key: "type"
            operator: Equal
            value: "app"
            effect: NoSchedule
      parameters:
        - name: 'elasticsearch.hosts[0]'
          value: 'elasticsearch-master-headless.logging.svc.cluster.local:9200'
    repoURL: 'https://kokuwaio.github.io/helm-charts'
    targetRevision: 11.15.0
