apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: keycloak
    helm:
      valueFiles:
        - values.yaml
      values: |-
        nodeSelector: {"type": "app"}
        tolerations:
          - key: "type"
            operator: Equal
            value: "app"
            effect: NoSchedule
      parameters:
        - name: postgresql.enabled
          value: 'false'
        - name: extraEnv
          value: |
            - name: DB_VENDOR
              value: mariadb
            - name: DB_ADDR
              value: mariadb-svr.mariadb.database.azure.com
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: keycloak?useSSL=true
            - name: DB_USER_FILE
              value: /secrets/db-creds/username
            - name: DB_PASSWORD_FILE
              value: /secrets/db-creds/password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_IMPORT
              value: /realm/cluster-realm.json
        - name: extraVolumeMounts
          value: |
            - name: db-creds
              mountPath: /secrets/db-creds
              readOnly: true
            - name: realm-secret
              mountPath: "/realm/"
              readOnly: true
        - name: extraVolumes
          value: |
            - name: db-creds
              secret:
                secretName: mariadb-secret
            - name: realm-secret
              secret:
                secretName: keycloak-realm-secret
    repoURL: 'https://codecentric.github.io/helm-charts'
    targetRevision: 18.1.1
