apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kiali-server
    helm:
      parameters:
        - name: auth.strategy
          value: anonymous
        - name: deployment.ingress_enabled
          value: 'false'
        - name: istio_namespace
          value: istio-system
      values: |-
        external_services:
          tracing:
            in_cluster_url: 'http://tracing.istio-system.svc.cluster.local/jaeger'
            url: 'https://vtch-aks-demo-monitoring.duckdns.org/jaeger'
    repoURL: 'https://kiali.org/helm-charts'
    targetRevision: 1.37.0
