apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: mailhog
    repoURL: 'https://codecentric.github.io/helm-charts'
    targetRevision: 4.1.0
