apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: mailhog
    repoURL: 'https://codecentric.github.io/helm-charts'
    targetRevision: 5.0.7
