apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-cert
  namespace: istio-system
spec:
  secretName: monitoring-cert
  commonName: monitoring.aks-demo.vtch.tech
  issuerRef:
    name: letsencrypt
  dnsNames:
    - monitoring.aks-demo.vtch.tech
