apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-cm
  namespace: default
data:
  database-url: jdbc:mariadb://mariadb-svr.mariadb.database.azure.com:3306/messaging?useSSL=true
  r2dbc-url: r2dbc:mariadb://mariadb-svr.mariadb.database.azure.com:3306/messaging