apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: persistence-api
  name: persistence-config
  namespace: default
data:
  application-prod.yml: |-
    application:
      hostname: https://aks-demo.vtch.tech
      token.url: https://aks-demo.vtch.tech/auth/realms/cluster/protocol/openid-connect/token
      kafka:
        bootstrapAddress: kafka-cluster-kafka-brokers.default.svc.cluster.local:9092
        groupId: persistenceApp
        topic: auditing
        stream:
          topic: reverse-auditing
      cors:
        allowed.origins: https://aks-demo.vtch.tech
        allowed.methods: GET, POST, PUT, DELETE
