apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: persistence-api
  name: persistence-config
  namespace: default
data:
  application-prod.yml: |-
    application:
      token.url: https://vtch-aks-demo.duckdns.org/auth/realms/cluster/protocol/openid-connect/token
      kafka:
        bootstrapAddress: kafka-cluster-kafka-brokers.default.svc.cluster.local:9092
        groupId: persistenceApp
        topic: auditing
        stream:
          topic: reverse-auditing
      cors:
        allowed.origins: "https://vtch-aks-demo.duckdns.org"
        allowed.methods: "GET", "POST", "PUT", "DELETE"