apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-api
  namespace: default
  labels:
    app: persistence-api
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: persistence-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: persistence-api
        auth: jwt
    spec:
      containers:
        - name: persistence-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mariadb-cm
                  key: database-url
            - name: SPRING_R2DBC_URL
              valueFrom:
                configMapKeyRef:
                  name: mariadb-cm
                  key: r2dbc-url
            - name: MANAGEMENT_SECURITY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: persistence-api-secret
                  key: actuator.username
            - name: MANAGEMENT_SECURITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: persistence-api-secret
                  key: actuator.password
          livenessProbe:
            httpGet:
              path: /persistence/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /persistence/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: grpc
              containerPort: 9090
          volumeMounts:
            - name: application-config
              mountPath: "/etc/config/"
      volumes:
        - name: application-config
          configMap:
            name: persistence-config
            items:
              - key: application-prod.yml
                path: application-prod.yml
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: persistence-service
  labels:
    app: persistence-service
    service: persistence-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/persistence/actuator/prometheus'
    prometheus.io/port: '8081'
spec:
  selector:
    app: persistence-api
  ports:
    - name: http2
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9090
      targetPort: 9090