apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
  namespace: istio-system
spec:
  secretName: kibana-cert
  commonName: kibana.aks-demo.vtch.tech
  issuerRef:
    name: letsencrypt
  dnsNames:
    - kibana.aks-demo.vtch.tech
