apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kibana-cert
  namespace: istio-system
spec:
  secretName: kibana-cert
  commonName: vtch-aks-demo-kibana.duckdns.org
  issuerRef:
    name: letsencrypt
  dnsNames:
    - vtch-aks-demo-kibana.duckdns.org