apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: istio-system
spec:
  secretName: prometheus-cert
  commonName: prometheus.aks-demo.vtch.tech
  issuerRef:
    name: letsencrypt
  dnsNames:
    - prometheus.aks-demo.vtch.tech
