name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    environment: Demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      env:
        CI_PASSWORD: ${{ secrets.CI_PASSWORD }}
  frontend:
    environment: Demo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build Frontend
      run: cd ./frontend && npm install && npm run build