apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.github: apiKey
  url: https://aks-demo.vtch.tech
  oidc.config: |
    name: Keycloak
    issuer: https://aks-demo.vtch.tech/auth/realms/cluster
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  repositories: |
    - type: git
      url: https://github.com/valtech-ch/microservice-kubernetes-cluster.git
  resource.customizations: |
    bitnami.com/SealedSecret:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Controller doesn't report resource status"
        return hs
